// Expansions lexicales du domaine (formation réglementaire) appliquées à la
// requête : un besoin exprimé avec les mots du visiteur retrouve les
// intitulés du référentiel. Clés et valeurs sont des tokens normalisés
// (sans accents) ; la valeur est racinisée comme les termes de l'index.
export const QUERY_SYNONYMS: Readonly<Record<string, readonly string[]>> = {
  secourisme: ['sst', 'secours'],
  secouriste: ['sst', 'secours'],
  secours: ['sst'],
  sst: ['secours', 'secouriste'],
  chariot: ['caces'],
  chariots: ['caces'],
  elevateur: ['caces'],
  nacelle: ['caces'],
  engin: ['caces'],
  engins: ['caces'],
  electricien: ['habilitation', 'electrique'],
  electricite: ['habilitation', 'electrique'],
  electrique: ['habilitation'],
  habilitation: ['electrique'],
  incendie: ['evacuation', 'extincteur'],
  extincteur: ['incendie'],
  hauteur: ['harnais', 'echafaudage'],
  echafaudage: ['hauteur'],
  amiante: ['ss4'],
  conflit: ['tension', 'mediation'],
  conflits: ['tension', 'mediation'],
  manager: ['management', 'encadrement'],
  managers: ['management', 'encadrement'],
  management: ['manager', 'encadrement'],
  informatique: ['numerique'],
  cyber: ['cybersecurite', 'securite'],
  rgpd: ['donnees', 'protection'],
  rse: ['durable', 'environnement'],
  qvt: ['sante', 'travail'],
  ergonomie: ['gestes', 'postures'],
  tms: ['gestes', 'postures'],
  // Verbes du besoin → substantifs des intitulés.
  gerer: ['gestion'],
  gere: ['gestion'],
  piloter: ['pilotage'],
  prevenir: ['prevention'],
  securiser: ['securite'],
  communiquer: ['communication'],
  negocier: ['negociation'],
  recruter: ['recrutement'],
  animer: ['animation'],
  encadrer: ['encadrement', 'management'],
  conduire: ['conduite'],
  evaluer: ['evaluation'],
  developper: ['developpement'],
  vendre: ['vente', 'commercial'],
  accueillir: ['accueil'],
  secourir: ['secours', 'sst'],
  proteger: ['protection', 'prevention']
}

/** Mots trop génériques dans un besoin de formation pour porter du sens. */
export const QUERY_NOISE: ReadonlySet<string> = new Set([
  'formation',
  'formations',
  'former',
  'forme',
  'formes',
  'formee',
  'formees',
  'stage',
  'stages',
  'cours',
  'besoin',
  'besoins',
  'salarie',
  'salaries',
  'collaborateur',
  'collaborateurs',
  'personne',
  'personnes',
  'equipe',
  'equipes',
  'cherche',
  'chercher',
  'cherchons',
  'souhaite',
  'souhaitons',
  'voudrais',
  'voudrions',
  'aimerais',
  'faut',
  'faire',
  'suivre',
  'apprendre',
  'nous',
  'notre',
  'entreprise',
  'societe',
  // Modaux, intensité, temps et lieu : le contexte de la demande, pas le
  // sujet de la formation.
  'doit',
  'doivent',
  'devons',
  'devez',
  'dois',
  'veut',
  'veulent',
  'voulons',
  'voulez',
  'souhaitent',
  'mieux',
  'moins',
  'vraiment',
  'rapidement',
  'vite',
  'urgent',
  'urgence',
  'bientot',
  'prochainement',
  'avant',
  'apres',
  'pendant',
  'depuis',
  'debut',
  'fin',
  'semaine',
  'semaines',
  'mois',
  'annee',
  'annees',
  'janvier',
  'fevrier',
  'mars',
  'avril',
  'mai',
  'juin',
  'juillet',
  'aout',
  'septembre',
  'octobre',
  'novembre',
  'decembre',
  'pres',
  'proche',
  'proximite',
  'autour',
  'environ',
  'region',
  'ville',
  'site',
  'sites',
  'obligatoire',
  'obligatoires',
  'reglementaire',
  'reglementaires',
  'nouveau',
  'nouvelle',
  'nouveaux',
  'nouvelles'
])
